version: 2

updates:
  # npm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '16:00'
      timezone: 'Europe/London'
    open-pull-requests-limit: 10
    versioning-strategy: 'increase'
    rebase-strategy: 'auto'
    labels:
      - 'dependencies'
    groups:
      minor-and-patch:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'

  # GitHub Actions updates
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '16:00'
      timezone: 'Europe/London'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'github-actions'
    groups:
      minor-and-patch:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
