sonar.organization=steverobertsuk
sonar.projectKey=steverobertsuk_sto-info-frontend

# Core settings
sonar.sources=src
sonar.tests=src,test
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/environments/**,**/constants/**,**/reports/**
sonar.javascript.lcov.reportPaths=reports/coverage/lcov.info

# Never require coverage for these
sonar.coverage.exclusions=\
src/main.ts,\
src/**/*.module.ts,\
src/environments/**,\
src/app/**/constants/**,\
src/**/*.model.ts,\
src/**/*.models.ts,\
src/**/*.interface.ts,\
src/**/*.interfaces.ts,\
src/**/*.enum.ts,\
src/**/*.constant.ts,\
src/**/*.constants.ts,\
src/main.ts,\
src/**/index.ts

# Ignore certain rules in test/spec files only
sonar.issue.ignore.multicriteria=e1,e2

# S1313: "Using hardcoded IP addresses is security-sensitive"
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S1313
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.spec.ts,**/*.test.ts,**/__tests__/**,**/test/**,**/tests/**

# S6684: "Hard-coded passwords are security-sensitive"
sonar.issue.ignore.multicriteria.e2.ruleKey=secrets:S6684
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.spec.ts,**/*.test.ts,**/__tests__/**,**/test/**,**/tests/**
