export const BASE_CLOUDFLARE_IMAGES_URL =
  'https://cdn.startrekonline.info/cdn-cgi/imagedelivery/jQ0uSdJ3ty-KasNpXGxyuA';
export const CLOUDFLARE_R2_PUBLIC_URL = 'https://cdn.startrekonline.info';
export const CLOUDFLARE_VARIANT_DEFAULT_NAME = 'public';
export const CLOUDFLARE_VARIANT_SQUARE_300PX_NAME = 'square300';
export const CLOUDFLARE_VARIANT_SQUARE_100PX_NAME = 'square100';

export const CLOUDFLARE_PHOTO_UNAVAILABLE_ID =
  '817e04f3-331f-4837-e189-c00a68e4c400';

export const SRC_PHOTO_UNAVAILABLE_MAIN = `${BASE_CLOUDFLARE_IMAGES_URL}/${CLOUDFLARE_PHOTO_UNAVAILABLE_ID}/${CLOUDFLARE_VARIANT_DEFAULT_NAME}`;
export const SRC_PHOTO_UNAVAILABLE_300PX = `${BASE_CLOUDFLARE_IMAGES_URL}/${CLOUDFLARE_PHOTO_UNAVAILABLE_ID}/${CLOUDFLARE_VARIANT_SQUARE_300PX_NAME}`;
export const SRC_PHOTO_UNAVAILABLE_100PX = `${BASE_CLOUDFLARE_IMAGES_URL}/${CLOUDFLARE_PHOTO_UNAVAILABLE_ID}/${CLOUDFLARE_VARIANT_SQUARE_100PX_NAME}`;
