export const MILLISECONDS_SHOW_ERROR_MSG = 15000;
export const MILLISECONDS_SHOW_RED_ALERT_THEME = 8000;
export const MILLISECONDS_SWITCH_TO_RED_ALERT_STATIC_THEME = 8000;

export const MILLISECONDS_API_HEALTH_CHECK_POLLING_INTERVAL = 60000;
export const MILLISECONDS_API_HEALTH_CHECK_TIMEOUT_INTERVAL = 2500;

export const MILLISECONDS_ZERO = 0;
