/**
 * User-facing Storytime copy.
 *
 * Held centrally rather than inline in templates so that a term is worded the
 * same everywhere it appears, and so a future localisation pass has one place
 * to work from. The application has no i18n today; this is the groundwork for
 * adding it without rewriting every template.
 *
 * British English throughout, matching the rest of the site.
 */
import {
  CONTENT_RATING_DESCRIPTIONS,
  CONTENT_RATING_LABELS,
  CompletionState,
  ContentRating,
} from 'src/app/models/storytime.models';
import type { SettingOption } from './shared/setting-help/setting-help.component';

export const STORYTIME_COPY = {
  /** The feature's name. Never abbreviated or pluralised. */
  FEATURE_NAME: 'Storytime',
  LANDING_TITLE: 'STO Storytime',
  LANDING_INTRO:
    'A permanent home for Star Trek Online fan stories, written and shared by the community.',
  LANDING_EMPTY:
    'There are no published Stories yet. Check back soon, or write the first one.',
  /**
   * The short-form notice, reproduced from the published Fan Content &
   * Intellectual Property Notice.
   *
   * That document nominates this wording for display on Storytime pages, so it
   * is quoted rather than paraphrased. Rewording it here would leave the site
   * making a claim about ownership that its own notice does not.
   */
  FAN_CONTENT_NOTICE:
    'STO Storytime contains unofficial, non-commercial fan-created works. Star Trek, Star Trek Online and related intellectual property belong to their respective rights holders. STO Info is an independent, non-commercial community project and is not affiliated with or endorsed by the owners or licensees of Star Trek or Star Trek Online. Story creators retain any rights they legally hold in their own original contributions.',
  CONTENT_POLICY_INTRO:
    'What may and may not be published through Storytime. It covers Stories, Chapters, Arcs, Characters, images, media, comments, credits and reading lists — everything submitted to or displayed through the feature.',
  TERMS_INTRO:
    'The agreement between you and STO Info about publishing here: what you keep, what you grant, and what STO Info may do about content that breaks the rules.',
  FAN_CONTENT_NOTICE_INTRO:
    'Who owns what. Storytime is unofficial, non-commercial fan work built on somebody else’s intellectual property, and this explains where the lines fall.',
  /**
   * Shown wherever a creator is asked to accept the terms for a Story.
   *
   * Worded as one act rather than three, because that is what it is: the three
   * documents are accepted together and recorded as one version.
   */
  POLICY_ACCEPTANCE_PROMPT:
    'Before this Story can be published, confirm it meets the Storytime publishing terms.',
  /**
   * Shown when a creator accepted wording that has since been replaced.
   *
   * Distinguished from never having accepted, because being told to do
   * something a second time is confusing without being told why.
   */
  POLICY_REACCEPTANCE_PROMPT:
    'The Storytime publishing terms have changed since you accepted them for this Story. Read them and confirm again before publishing.',
} as const;

/**
 * Which version of the publishing terms this build presents.
 *
 * Shown on the three documents so a creator can tell what they agreed to. The
 * server holds the same value and is the one that decides whether a Story's
 * acceptance is current — this copy is for display only, because a stale
 * bundle disagreeing with the server must not change what may be published.
 */
export const STORYTIME_POLICY_VERSION = '1.0';

/**
 * When the current version of the publishing terms took effect.
 */
export const STORYTIME_POLICY_EFFECTIVE_DATE = '18th August 2026';

/**
 * What a creator confirms when they accept the publishing terms.
 *
 * These are the representations the Terms of Use require (§10) and the Content
 * Policy repeats (§25). They are listed at the point of acceptance rather than
 * left behind a link, because a creator who has not read them is exactly the
 * creator the representations are about.
 */
export const PUBLISHING_REPRESENTATIONS: readonly string[] = [
  'You are entitled to submit the content.',
  'You have any permissions reasonably required from other contributors.',
  'You have not knowingly plagiarised another creator.',
  'Anything you uploaded is yours, licensed to you, or otherwise lawful for you to use.',
  'Crew and contributor credits are genuine.',
  'You have chosen an appropriate content rating.',
  'The content meets the Storytime Content Policy.',
  'You are not presenting the work as official Star Trek or Star Trek Online material.',
  'The substantive writing is your own, not generated by AI.',
  'You are not using Storytime to sell, paywall or otherwise monetise the work.',
];

/**
 * What the Storytime content policy covers.
 *
 * The categories are the ones the feature actually enforces: a reporter picks
 * from this list and an administrator cites it when removing something, so the
 * three surfaces cannot describe the rules differently.
 *
 * Each summary condenses a section of the published Content Policy and names
 * it, so a reader who wants the full wording knows where to look and a future
 * revision of the document has an obvious place to land. The `code` values
 * match the reasons the server accepts; changing one changes what the API is
 * told.
 */
export const CONTENT_POLICY_RULES = [
  {
    code: 'HARASSMENT',
    title: 'Harassment',
    section: '13',
    summary:
      'Nothing that targets, threatens or persistently pursues a real person. Fiction may explore conflict; it may not be used to attack somebody.',
  },
  {
    code: 'HATE_CONTENT',
    title: 'Hate content',
    section: '13',
    summary:
      'Nothing that demeans people for who they are. A prejudiced character in a story is not the same as a story endorsing prejudice, but the difference has to be visible.',
  },
  {
    code: 'EXPLICIT_CONTENT',
    title: 'Explicit sexual content',
    section: '11',
    summary:
      'Written sexual content must stay within what your Story’s rating declares. Explicit images and video are never permitted, and characters who are minors must never be sexualised.',
  },
  {
    code: 'GRAPHIC_VIOLENCE',
    title: 'Graphic violence',
    section: '12',
    summary:
      'Fictional violence is welcome and should be rated for its intensity. Real-world violence published for shock, and anything that encourages it, is not.',
  },
  {
    code: 'PLAGIARISM',
    title: 'Plagiarism',
    section: '7',
    summary:
      'Post your own writing. Two creators may share the same established characters and places; neither may take the other’s prose, original characters or artwork.',
  },
  {
    code: 'IMPERSONATION',
    title: 'Impersonation',
    section: '8, 19',
    summary:
      'Do not write as another member, a developer, or the site itself, and do not claim a real person took part in your Story without their agreement.',
  },
  {
    code: 'PERSONAL_INFORMATION',
    title: 'Personal information',
    section: '14',
    summary:
      'Nobody’s real-world details without their agreement — including your own, for your sake.',
  },
  {
    code: 'COPYRIGHT',
    title: 'Copyright',
    section: '4, 6, 24',
    summary:
      'Fan work is welcome. Using somebody’s artwork, music, recordings or writing without permission is not, and crediting them is not the same as asking them.',
  },
  {
    code: 'AI_GENERATED_CONTENT',
    title: 'AI-generated writing',
    section: '9',
    summary:
      'Stories and Chapters written by generative AI are not permitted. Spelling, grammar and accessibility help does not count — writing the story for you does.',
  },
  {
    code: 'COMMERCIAL_CONTENT',
    title: 'Selling and advertising',
    section: '3, 18',
    summary:
      'Storytime is non-commercial. No paywalls, paid early access, affiliate links, sponsorship or solicitation. What you do professionally elsewhere is your own business.',
  },
  {
    code: 'SPAM',
    title: 'Spam',
    section: '18',
    summary: 'No scams, phishing or repetition dressed up as a Story.',
  },
  {
    code: 'MALICIOUS_LINK',
    title: 'Malicious links',
    section: '17',
    summary:
      'No links that lead somewhere harmful, and no disguised addresses or redirects used to get around the link rules.',
  },
  {
    code: 'DECEPTIVE_MEDIA',
    title: 'Deceptive media',
    section: '16, 19',
    summary:
      'Do not present media as something it is not, or fan-made material as an official Star Trek Online announcement.',
  },
] as const;

/**
 * How each report reason reads in the moderation queue.
 *
 * Built from the policy so the queue can never describe a category one way
 * while the policy page describes it another.
 */
export const REPORT_REASON_LABELS: Record<string, string> = {
  ...Object.fromEntries(
    CONTENT_POLICY_RULES.map(rule => [rule.code, rule.title]),
  ),
  OTHER: 'Something else',
};

/**
 * The reasons somebody may pick when reporting content.
 *
 * The policy categories plus "something else", which exists because a list
 * that covers everything is a list nobody reads to the end of.
 */
export const REPORT_REASONS = [
  ...CONTENT_POLICY_RULES.map(rule => ({
    code: rule.code,
    label: rule.title,
    description: rule.summary,
  })),
  {
    code: 'OTHER',
    label: 'Something else',
    description:
      'Anything the categories above do not cover. Say what is wrong in your own words.',
  },
];

/**
 * How each tag category is named to a reader.
 *
 * The categories are fixed in the database; these are the words shown for
 * them, held here so a picker, a filter and a Story page agree.
 */
export const TAG_CATEGORY_LABELS: Record<string, string> = {
  FACTION: 'Faction',
  ERA: 'Era',
  GENRE: 'Genre',
  TONE: 'Tone',
  THEME: 'Theme',
  SPECIES: 'Species',
  CONTENT_WARNING: 'Content warning',
  FORMAT: 'Format',
  CONTINUITY: 'Continuity',
};

/**
 * What each tag category is for.
 *
 * Shown beside the category chooser rather than under it: a select's own
 * container is a solid colour, so a line of hint text inside one is a line
 * nobody can read. The same reason the content rating and visibility choices
 * explain themselves through a help popup.
 */
export const TAG_CATEGORY_DESCRIPTIONS: Record<string, string> = {
  FACTION: 'Which power the Story belongs to: Federation, Klingon and so on.',
  ERA: 'When the Story is set, by the period of Star Trek it belongs to.',
  GENRE: 'The shape of the Story: mystery, romance, war, exploration.',
  TONE: 'How the Story reads: light, bleak, comic, hopeful.',
  THEME: 'What the Story is about underneath its plot.',
  SPECIES: 'A species the Story is substantially about.',
  CONTENT_WARNING: 'Something a reader may want to know before they start.',
  FORMAT: 'How the Story is written: log entries, letters, a script.',
  CONTINUITY: 'Which continuity the Story treats as true.',
};

/**
 * The kinds of content a reader may search, and how each is named.
 *
 * The empty code means "everything", which is the default and the first tab: a
 * reader searching for a name rarely knows whether it belongs to a Story, a
 * Chapter or a Character.
 */
export const SEARCHABLE_KINDS = [
  { code: '', label: 'Everything' },
  { code: 'STORY', label: 'Stories' },
  { code: 'CHAPTER', label: 'Chapters' },
  { code: 'CHARACTER', label: 'Characters' },
  { code: 'ARC', label: 'Arcs' },
] as const;

/**
 * How long to wait after a reader stops scrolling before recording where they
 * are.
 *
 * A scroll fires continuously, so without a pause a reader moving down a long
 * Chapter would send a request per frame. Long enough to collapse a scroll
 * into one write, short enough that closing the tab shortly after reading does
 * not lose the position.
 */
export const PROGRESS_WRITE_DEBOUNCE_MS = 5000;

/**
 * How each reader-facing Story status is labelled.
 *
 * The single authoritative mapping, so a status never reads one way in a
 * library filter and another on a Story page. Raw enum values are never shown
 * to readers.
 */
export const READER_STORY_STATUS_LABELS = {
  NOT_STARTED: 'Not started',
  IN_PROGRESS: 'In progress',
  COMPLETED: 'Completed',
  ON_HOLD: 'On hold',
  ABANDONED: 'Abandoned',
} as const;

/**
 * How each collaboration invitation status is labelled.
 */
export const COLLABORATION_STATUS_LABELS = {
  INVITED: 'Invited',
  ACCEPTED: 'Collaborating',
  DECLINED: 'Declined',
  REVOKED: 'No longer collaborating',
} as const;

/**
 * The capabilities an invitation may grant, and how each is described.
 *
 * Publishing is deliberately absent: only the owner may publish, so offering a
 * switch that could never be turned on would be worse than saying nothing.
 */
export const COLLABORATOR_CAPABILITIES = [
  { key: 'canEditStory', label: 'Edit the Story’s details' },
  { key: 'canManageChapters', label: 'Write and edit Chapters' },
  { key: 'canManageCharacters', label: 'Manage the cast' },
  { key: 'canManageCrew', label: 'Manage the credits' },
  { key: 'canManageCollaborators', label: 'Invite other collaborators' },
] as const;

/**
 * The capabilities an Arc invitation may grant, and how each is described.
 *
 * Publishing is absent for the same reason it is absent from a Story
 * invitation: deciding an Arc is ready to show the world stays with the
 * curator, so there is no switch to offer.
 */
export const ARC_COLLABORATOR_CAPABILITIES = [
  { key: 'canEditArc', label: 'Edit the Arc’s details' },
  { key: 'canManageStories', label: 'Choose which Stories are in it' },
  { key: 'canManageCollaborators', label: 'Invite other collaborators' },
] as const;

/**
 * How each Arc membership status is labelled.
 *
 * `INVITED` and `REQUESTED` are worded from the curator's side, because that
 * is where the list they appear in lives.
 */
export const ARC_MEMBERSHIP_STATUS_LABELS = {
  REQUESTED: 'Asked to join',
  INVITED: 'Invited',
  APPROVED: 'In the Arc',
  DECLINED: 'Declined',
  REMOVED: 'Removed',
  WITHDRAWN: 'Withdrawn',
} as const;

/**
 * How each reader-facing Chapter status is labelled.
 */
export const READER_CHAPTER_STATUS_LABELS = {
  UNREAD: 'Unread',
  IN_PROGRESS: 'In progress',
  READ: 'Read',
} as const;

/**
 * How a creator's own publication states are labelled.
 */
export const PUBLICATION_STATUS_LABELS = {
  DRAFT: 'Draft',
  IN_REVIEW: 'In review',
  SCHEDULED: 'Scheduled',
  PUBLISHED: 'Published',
  UNPUBLISHED: 'Unpublished',
  ARCHIVED: 'Archived',
} as const;

/**
 * How each completion state is described to readers.
 */
export const COMPLETION_STATE_LABELS = {
  ONGOING: 'Ongoing',
  COMPLETED: 'Complete',
  HIATUS: 'On hiatus',
  CANCELLED: 'Cancelled',
} as const;

/**
 * What each completion state tells readers about a Story.
 */
export const COMPLETION_STATE_DESCRIPTIONS = {
  ONGOING: 'The Story is still being written.',
  COMPLETED: 'The Story has reached its planned ending.',
  HIATUS: 'The Story is paused and may continue later.',
  CANCELLED: 'The Story will not receive any more Chapters.',
} as const;

/**
 * The ratings, as something that explains itself.
 *
 * A creator chooses one of these and a reader is told which was chosen, and
 * both need the same words for what it means — so the pair is built once here
 * rather than in the editor that sets it and again on the page that reports
 * it.
 */
export const CONTENT_RATING_OPTIONS: readonly SettingOption[] = Object.values(
  ContentRating,
).map(rating => ({
  value: rating,
  label: CONTENT_RATING_LABELS[rating],
  description: CONTENT_RATING_DESCRIPTIONS[rating],
}));

/** The completion states, explained the same way and for the same reason. */
export const COMPLETION_STATE_OPTIONS: readonly SettingOption[] = Object.values(
  CompletionState,
).map(state => ({
  value: state,
  label: COMPLETION_STATE_LABELS[state],
  description: COMPLETION_STATE_DESCRIPTIONS[state],
}));

/**
 * How each visibility option is described to creators.
 */
export const VISIBILITY_LABELS = {
  PUBLIC: 'Public',
  UNLISTED: 'Unlisted',
  PRIVATE: 'Private',
} as const;

/**
 * The icon standing for each visibility, on a creator's own list of works.
 *
 * A row carries its visibility as a mark rather than a word, the way a captain
 * card carries its recruit type: the list is scanned rather than read, and
 * three shapes are told apart faster than three words. Each is paired with its
 * label for anyone not reading the screen.
 *
 * Read as a set: seen by anyone, reached by link, or locked. The site's Font
 * Awesome kit is subsetted, so an icon has to be one it actually carries —
 * `fa-globe` for instance is not in it, and renders as an empty circle.
 */
export const VISIBILITY_ICONS = {
  PUBLIC: 'fa-eye',
  UNLISTED: 'fa-link',
  PRIVATE: 'fa-lock',
} as const;

/**
 * What each visibility option actually means, shown alongside the choice so a
 * creator is not left guessing how far their Story travels.
 */
export const VISIBILITY_DESCRIPTIONS = {
  PUBLIC: 'Listed in the archive and readable by anyone.',
  UNLISTED: 'Readable by anyone with the link, but not listed in the archive.',
  PRIVATE: 'Readable only by you.',
} as const;
