name: 'Get & Cache Dependencies'
description: 'Get the dependencies (via npm) and cache them.'

runs:
  using: 'composite'
  steps:
    - name: Cache Node modules
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies (first run or when lockfile changes)
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash

    - name: Use cached dependencies
      if: steps.cache.outputs.cache-hit == 'true'
      run: echo "Using cached node_modules from GitHub cache."
      shell: bash
