name: 'Setup Project'
description: 'Checkout code, set up Node.js, and set up .npmrc file'

inputs:
  node-version:
    description: 'Node.js version'
    required: true
    default: 22

  fontawesome-npm-auth-token:
    description: 'FontAwesome NPM Auth Token'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup .npmrc file to publish to npm
      run: |
        echo "//npm.fontawesome.com/:_authToken=${{ inputs.fontawesome-npm-auth-token }}" > .npmrc
      shell: bash
