name: 'Setup Project'
description: 'Set up Node.js'

inputs:
  node-version:
    description: 'Node.js version'
    required: true
    default: '24'

runs:
  using: 'composite'

  steps:
    - name: Use Node.js
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: ${{ inputs.node-version }}
