name: Angular CI

on:
  pull_request:
    branches:
      - development
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

env:
  NODE_VERSION: 18

jobs:
  angular_ci_lint:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup project
        uses: ./.github/actions/setup-project
        with:
          node-version: ${{ env.NODE_VERSION }}
          fontawesome-npm-auth-token: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

      - name: Load & cache dependencies
        uses: ./.github/actions/cached-dependencies

      - name: Lint code
        run: npm run lint

  angular_ci_test:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup project
        uses: ./.github/actions/setup-project
        with:
          node-version: ${{ env.NODE_VERSION }}
          fontawesome-npm-auth-token: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

      - name: Load & cache dependencies
        uses: ./.github/actions/cached-dependencies

      - name: Test code
        id: run-tests
        run: npm run test

  angular_ci_version_bump:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Bump version (patch)
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GH_PAT_REPO_TOKEN }}
          default_bump: patch
          tag_prefix: v
          create_annotated_tag: false # do not create a tag yet

      - name: Update version in package.json
        run: npm version --no-git-tag-version ${{ steps.tag_version.outputs.new_version }}

      - name: Get new version
        id: get_version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

  angular_ci_build:
    if: github.actor != 'github-actions[bot]'
    needs: [angular_ci_lint, angular_ci_test, angular_ci_version_bump]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup project
        uses: ./.github/actions/setup-project
        with:
          node-version: ${{ env.NODE_VERSION }}
          fontawesome-npm-auth-token: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

      - name: Load & cache dependencies
        uses: ./.github/actions/cached-dependencies

      - name: Build website
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist

  angular_ci_version_and_tag:
    if: github.actor != 'github-actions[bot]'
    needs:
      [
        angular_ci_lint,
        angular_ci_test,
        angular_ci_version_bump,
        angular_ci_build,
      ]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT_REPO_TOKEN }}

      - name: Create and push tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag v${{ needs.angular_ci_version_bump.outputs.get_version.outputs.version }} # create the tag
          git push origin v${{ needs.angular_ci_version_bump.outputs.get_version.outputs.version }} # push the tag
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_REPO_TOKEN }}

  angular_ci_deploy_to_dev:
    needs:
      [
        angular_ci_lint,
        angular_ci_test,
        angular_ci_build,
        angular_ci_version_and_tag,
      ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
          path: dist

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Sync dist folder to S3
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: dev.startrekonline.info
          SOURCE_DIR: 'dist/sto-info-frontend'
          ACL: 'public-read'
          ARGS: '--delete'

  # angular_ci_is_done:
  #   needs: [angular_ci_deploy_to_dev]
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 1
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Completion Step
  #       uses: ./.github/actions/workflow-complete
