name: Development Pull Request CI - Version Bump

on:
  workflow_run:
    workflows: ['Development Pull Request CI - Lint and Test']
    types:
      - completed

env:
  NODE_VERSION: 18

jobs:
  version_bump:
    if: "github.event.workflow_run.conclusion == 'success' && !startsWith(github.event.workflow_run.head_commit.message, 'Bump version to')"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GH_PAT_REPO_TOKEN }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get current version
        id: current_version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Bump version (patch) in package.json
        id: bump_version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npm version patch -m "Bump version to %s"
          echo "::set-output name=new_version::$(node -p "require('./package.json').version")"

      - name: Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git push https://x-access-token:${{ secrets.GH_PAT_REPO_TOKEN }}@github.com/steverobertsuk/sto-info-frontend.git HEAD:${{ github.event.pull_request.head.ref }}
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_REPO_TOKEN }}

      - name: Check version bump
        run: |
          if [[ "${{ steps.current_version.outputs.version }}" == "${{ steps.bump_version.outputs.new_version }}" ]]; then
            echo "Version bump failed."
            exit 1
          fi

      - name: Bump version (patch) in Git
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GH_PAT_REPO_TOKEN }}
          default_bump: false
          tag_prefix: v
          release_branches: development
          # create_annotated_tag: false # do not create a tag yet
