name: Angular CI

on:
  push:
    branches:
      - development
      - production
  workflow_dispatch:

env:
  NODE_VERSION: 18

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup project
        uses: ./.github/actions/setup-project
        with:
          node-version: ${{ env.NODE_VERSION }}
          fontawesome-npm-auth-token: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

      - name: Load & cache dependencies
        uses: ./.github/actions/cached-dependencies

      - name: Lint code
        run: npm run lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup project
        uses: ./.github/actions/setup-project
        with:
          node-version: ${{ env.NODE_VERSION }}
          fontawesome-npm-auth-token: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

      - name: Load & cache dependencies
        uses: ./.github/actions/cached-dependencies

      - name: Test code
        id: run-tests
        run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup project
        uses: ./.github/actions/setup-project
        with:
          node-version: ${{ env.NODE_VERSION }}
          fontawesome-npm-auth-token: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

      - name: Load & cache dependencies
        uses: ./.github/actions/cached-dependencies

      - name: Build website
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist

  version_and_tag:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
