name: 'Dependency Review'

on:
  pull_request:
    branches: ['development', 'production']
    types: [opened, synchronize, reopened, ready_for_review]

env:
  NODE_VERSION: 24.15.0

permissions: {}

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      pkg_changed: ${{ steps.filter.outputs.pkg_changed }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: filter
        with:
          filters: |
            pkg_changed:
              - 'package.json'
              - 'package-lock.json'

  dependency-review:
    name: 'Dependency Review'
    needs: check_changes
    if: needs.check_changes.outputs.pkg_changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          # Possible values: "critical", "high", "moderate", "low"
          fail-on-severity: high
