name: Mutation Testing (Full)

on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight
  workflow_dispatch: # Allow manual trigger

# Declare default permissions as none.
permissions: {}

env:
  NODE_VERSION: 24

jobs:
  stryker_full:
    name: Full Mutation Analysis
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 180
    permissions:
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Load & cache dependencies
        uses: ./.github/actions/cached-dependencies
        with:
          use-cache: true
          node-version: ${{ env.NODE_VERSION }}

      - name: Create test environment.ts
        run: |
          mkdir -p src/environments
          cat << 'EOF' > src/environments/environment.ts
          import packageJson from '../../package.json';
          import type { Environment } from './models/environment.model';

          export const environment: Environment = {
            production: false,
            version: packageJson.version,
            env_name: 'ci',
            env_label: 'CI',
            apiUrl: 'http://localhost:3000',
            appTitle: 'STO Info (CI)',
            appLoggedInHome: '/dashboard',
            allowDebugging: false,
            minsBeforeLogoutExpiryToShowWarning: 5,
            minsBeforeLogoutExpiryToRefreshToken: 2,
            cookieYesUrl: 'https://cdn-cookieyes.com/client_data/test/script.js',
            gaMeasurementId: 'G-XXXXXXX',
            logRocketAppId: 'test/appid',
          };
          EOF

      - name: Run Stryker (Full)
        run: npx stryker run

      - name: Upload Mutation Report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: stryker-full-report
          path: reports/mutation/
          retention-days: 30
