name: Version Bump

on:
  workflow_dispatch:

  # Check pull request comment when it is created
  pull_request_review_comment:
    types: [created]

env:
  BUMP_VERSION_COMMIT_MSG: 'Bump version number'

jobs:
  prerequisite_check:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    outputs:
      skip: ${{ steps.commit.outputs.skip }}
      branch: ${{ steps.get_branch_name.outputs.branch }}
      do_version_bump: ${{ steps.check_comment.outputs.do_version_bump }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: commit
        name: Get commit message
        run: |
          COMMIT_MESSAGE=$(git log --no-merges -1 --format=%B)
          echo "Current commit message: $COMMIT_MESSAGE"
          if [[ "$COMMIT_MESSAGE" == "${{ env.BUMP_VERSION_COMMIT_MSG }}"* ]]; then
            echo "::set-output name=skip::true"
          else
            echo "::set-output name=skip::false"
          fi
        shell: bash

      - id: get_branch_name
        name: Get branch name
        run: |
          if [ -n "${GITHUB_HEAD_REF}" ]; then
            branch_name=${GITHUB_HEAD_REF}
          else
            branch_name=${GITHUB_REF#refs/heads/}
          fi
          echo "Branch name is: $branch_name"
          echo "::set-output name=branch::$branch_name"
        shell: bash

      - id: check_comment
        name: Check for /bump_version comment
        if: ${{ github.event_name == 'issue_comment' }}
        run: |
          COMMENT_BODY="${{ github.event.comment.body }}"
          if [[ "$COMMENT_BODY" == *"/bump_version"* ]]; then
            echo "::set-output name=do_version_bump::true"
          else
            echo "::set-output name=do_version_bump::false"
          fi
        shell: bash

      - name: Print Outputs
        run: |
          echo "skip: ${{ steps.commit.outputs.skip }}"
          echo "branch: ${{ steps.get_branch_name.outputs.branch }}"
          echo "do_version_bump: ${{ steps.check_comment.outputs.do_version_bump }}"

  version_bump:
    needs: prerequisite_check
    if: needs.prerequisite_check.outputs.skip != 'true' && needs.prerequisite_check.outputs.branch != '' && needs.prerequisite_check.outputs.do_version_bump == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Set Environment Variables
        run: |
          echo "BRANCH_NAME=${{ needs.prerequisite_check.outputs.branch }}" >> $GITHUB_ENV
          echo "SKIP=${{ needs.prerequisite_check.outputs.skip }}" >> $GITHUB_ENV
          echo "DO_VERSION_BUMP=${{ needs.prerequisite_check.outputs.do_version_bump }}" >> $GITHUB_ENV

      - name: Print Environment Variables
        run: printenv

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT_REPO_TOKEN }}
          fetch-depth: 0 # Fetch all history to enable proper commit and push

      - name: Debug Branch Name
        run: |
          echo "Branch to push to: $BRANCH_NAME"

      - name: Get Old App Version
        id: old-app-ver
        run: |
          version=$(jq -r '.version' package.json)
          echo "::set-output name=version::$version"
          echo "Old version: $version"

      - name: Bump Version and Push Changes Back
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          npm version patch -m "${{ env.BUMP_VERSION_COMMIT_MSG }} from ${{ steps.old-app-ver.outputs.version }} to %s"
          echo "Pushing to branch: $branch_name"
          git push origin HEAD:$branch_name
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_REPO_TOKEN }}
